import { StyleSheet } from "react-native";

export const examStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#F4F6FB" },
  content: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 40,
    gap: 14,
  },
  pageTitle: {
    fontSize: 32,
    fontWeight: "700",
    color: "#111827",
    lineHeight: 38,
    marginBottom: 2,
  },

  // ── Tab switcher (Шалгалтуудад / Шалгалтын түүх) ──
  tabRow: {
    flexDirection: "row",
    backgroundColor: "#EEF2FF",
    borderRadius: 22,
    padding: 4,
  },
  tab: {
    flex: 1,
    paddingVertical: 10,
    alignItems: "center",
    borderRadius: 18,
  },
  tabActive: {
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  tabText: {
    fontSize: 14,
    fontWeight: "500",
    color: "#64748B",
  },
  tabTextActive: {
    color: "#111827",
  },

  // ── Search bar ──
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 8,
    minHeight: 48,
    borderWidth: 1,
    borderColor: "#DCE4FF",
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: "#111",
  },
  searchPlaceholderText: {
    fontSize: 14,
    color: "#AAB0C0",
  },
  searchIcon: {
    fontSize: 16,
    color: "#AAB0C0",
  },

  // ── Empty state ──
  emptyCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 28,
    alignItems: "center",
    gap: 12,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
  },
  emptyEmoji: { fontSize: 48 },
  emptyTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#111",
    textAlign: "center",
  },
  emptyText: {
    fontSize: 14,
    color: "#888",
    textAlign: "center",
    lineHeight: 20,
  },

  // ── Exam detail card (active exam header) ──
  preflightWrap: {
    flex: 1,
    minHeight: 520,
    justifyContent: "center",
    paddingVertical: 24,
  },
  preflightCard: {
    backgroundColor: "#fff",
    borderRadius: 28,
    paddingHorizontal: 24,
    paddingVertical: 28,
    alignItems: "center",
    gap: 16,
    borderWidth: 1,
    borderColor: "#DCE4FF",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  preflightIcon: {
    width: 88,
    height: 88,
    borderRadius: 28,
    backgroundColor: "#EEF4FF",
    alignItems: "center",
    justifyContent: "center",
  },
  preflightTitle: {
    fontSize: 22,
    lineHeight: 28,
    fontWeight: "800",
    color: "#111827",
    textAlign: "center",
  },
  preflightText: {
    fontSize: 14,
    lineHeight: 22,
    color: "#667085",
    textAlign: "center",
  },
  preflightMeta: {
    width: "100%",
    borderRadius: 18,
    backgroundColor: "#F8FAFF",
    borderWidth: 1,
    borderColor: "#E5ECFF",
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 4,
  },
  preflightMetaLabel: {
    fontSize: 13,
    color: "#6B7280",
  },
  preflightMetaValue: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "700",
    color: "#111827",
  },
  activeExamLayout: {
    gap: 14,
    marginBottom: 2,
  },
  activeExamHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 14,
  },
  activeExamHeading: {
    flex: 1,
    gap: 8,
    paddingTop: 4,
  },
  activeExamTitle: {
    fontSize: 18,
    lineHeight: 26,
    fontWeight: "800",
    color: "#111827",
  },
  activeExamSubtitle: {
    fontSize: 15,
    lineHeight: 23,
    color: "#9AA0AA",
  },
  examTimerBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#D7DDE8",
    backgroundColor: "#FFFFFF",
  },
  examTimerBadgeText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#111827",
  },
  subtleStatusText: {
    fontSize: 13,
    lineHeight: 19,
    color: "#6B7280",
  },
  examCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
  },
  examCardTop: { height: 5, backgroundColor: "#5B67F8" },
  examCardBody: { padding: 16, gap: 12 },
  examCardRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  avatar: {
    width: 46,
    height: 46,
    borderRadius: 14,
    backgroundColor: "#7C6FE0",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: { color: "#fff", fontSize: 18, fontWeight: "800" },
  examTitle: { fontSize: 15, fontWeight: "700", color: "#111" },
  examMeta: { fontSize: 12, color: "#888", marginTop: 2 },

  // ── List card (шалгалтын жагсаалтын card) ──
  listCard: {
    backgroundColor: "#fff",
    borderRadius: 18,
    padding: 16,
    gap: 6,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  listCardRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  listCardTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#111",
    flex: 1,
    marginRight: 8,
  },
  listCardMeta: {
    fontSize: 12,
    color: "#888",
    lineHeight: 19,
  },
  upcomingCard: {
    backgroundColor: "#fff",
    borderRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 14,
    minHeight: 198,
    gap: 18,
    borderWidth: 1,
    borderColor: "#DCE4FF",
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  upcomingCardTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111827",
    flex: 1,
    marginRight: 10,
    lineHeight: 24,
  },
  upcomingMetaGroup: {
    gap: 16,
  },
  upcomingMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  upcomingMetaLabel: {
    fontSize: 16,
    color: "#A3A3A3",
    flex: 1,
  },
  upcomingMetaValue: {
    fontSize: 16,
    fontWeight: "400",
    color: "#111827",
  },
  upcomingPrimaryButton: {
    marginTop: 4,
    marginLeft: "auto",
    minWidth: 172,
    backgroundColor: "#4F46E5",
    borderRadius: 22,
    paddingVertical: 15,
    paddingHorizontal: 28,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#4F46E5",
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 3,
  },
  upcomingButtonRow: {
    marginTop: "auto",
    gap: 12,
    width: "100%",
  },
  upcomingDivider: {
    height: 1,
    backgroundColor: "#E6ECFF",
  },
  upcomingDetailButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 6,
    minHeight: 36,
  },
  upcomingDetailText: {
    fontSize: 15,
    fontWeight: "500",
    color: "#111827",
    lineHeight: 20,
  },
  upcomingDetailArrow: {
    marginRight: -4,
  },
  detailLink: {
    fontSize: 13,
    color: "#5B67F8",
    fontWeight: "600",
    marginTop: 4,
    alignSelf: "flex-end",
  },

  // ── Status pills ──
  statusPill: {
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 6,
    backgroundColor: "#E8FBEE",
  },
  statusPillNeutral: { backgroundColor: "#EEF2F7" },
  statusPillWarning: { backgroundColor: "#FEF3C7" },
  statusPillDanger: { backgroundColor: "#FEE2E2" },
  statusPillText: { color: "#22C55E", fontSize: 12, fontWeight: "500" },
  statusPillTextNeutral: { color: "#6B7280" },
  statusPillTextWarning: { color: "#B45309" },
  statusPillTextDanger: { color: "#DC2626" },

  // ── Meta chips (remaining time / progress) ──
  metaRow: { flexDirection: "row", gap: 10 },
  metaChip: {
    flex: 1,
    backgroundColor: "#F2F4F7",
    borderRadius: 14,
    padding: 12,
    alignItems: "center",
  },
  metaChipLabel: { fontSize: 11, color: "#888", marginBottom: 4 },
  metaChipValue: { fontSize: 18, fontWeight: "800", color: "#111" },

  // ── Info / warning / error boxes ──
  infoBox: { backgroundColor: "#EEF4FF", borderRadius: 12, padding: 10 },
  infoText: { color: "#3657B0", fontSize: 13, lineHeight: 19 },
  warningBox: { backgroundColor: "#FEF3C7", borderRadius: 12, padding: 10 },
  warningText: { color: "#B45309", fontSize: 13 },
  errorText: { color: "#DC2626", fontSize: 13, textAlign: "center" },

  // ── Buttons ──
  primaryBtn: {
    backgroundColor: "#5B67F8",
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center",
  },
  primaryBtnText: { color: "#fff", fontWeight: "700", fontSize: 15 },
  secondaryBtn: {
    backgroundColor: "#F2F4F7",
    borderRadius: 14,
    paddingVertical: 13,
    alignItems: "center",
  },
  secondaryBtnText: { color: "#5B67F8", fontWeight: "600", fontSize: 15 },

  // ── Question card ──
  questionCard: {
    backgroundColor: "#fff",
    borderRadius: 24,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 16,
    gap: 16,
    borderWidth: 1,
    borderColor: "#DCE4FF",
  },
  questionCounter: { fontSize: 14, fontWeight: "500", color: "#7183A3" },
  questionText: {
    fontSize: 18,
    fontWeight: "800",
    color: "#111827",
    lineHeight: 30,
  },
  questionImage: {
    width: "100%",
    height: 180,
    borderRadius: 14,
    backgroundColor: "#F2F4F7",
  },
  optionList: { gap: 10 },
  optionContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
  },
  optionButton: {
    borderWidth: 1,
    borderColor: "#DCE3EE",
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 18,
    backgroundColor: "#F4F7FB",
  },
  optionButtonSelected: {
    borderColor: "#3568F5",
    backgroundColor: "#BFD0FF",
  },
  optionLabel: { fontSize: 17, color: "#1F2A44", lineHeight: 24 },
  optionLabelSelected: { color: "#1F2A44", fontWeight: "800" },
  answerInput: {
    minHeight: 160,
    borderWidth: 1.5,
    borderColor: "#E0E3F0",
    borderRadius: 18,
    backgroundColor: "#F4F7FB",
    padding: 14,
    textAlignVertical: "top",
    fontSize: 16,
    color: "#111827",
  },

  // ── Footer navigation ──
  footerActions: { gap: 10, paddingBottom: 8 },
  questionFooterRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  footerSpacer: {
    width: 44,
  },
  navIconBtn: {
    width: 44,
    height: 44,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#DCE4FF",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  questionPrimaryBtn: {
    flex: 1,
    backgroundColor: "#3568F5",
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  questionPrimaryBtnDisabled: {
    backgroundColor: "#A9C0F7",
  },
  questionPrimaryBtnText: {
    color: "#FFFFFF",
    fontWeight: "800",
    fontSize: 18,
    lineHeight: 22,
  },
  navBtn: {
    backgroundColor: "#F2F4F7",
    borderRadius: 14,
    paddingVertical: 13,
    alignItems: "center",
  },
  navBtnDisabled: { opacity: 0.4 },
  navBtnText: { color: "#5B67F8", fontWeight: "600", fontSize: 15 },

  detailOverlay: {
    flex: 1,
    backgroundColor: "#F8FAFC",
  },
  detailSheet: {
    backgroundColor: "#F8FAFC",
    flex: 1,
  },
  detailTopBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    minHeight: 56,
    paddingTop: 8,
    paddingBottom: 8,
  },
  detailBackButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  detailHeaderTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111827",
    lineHeight: 22,
  },
  detailHeaderSpacer: {
    width: 44,
  },
  detailContent: {
    padding: 16,
    gap: 18,
  },
  detailHeroCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#D8E3FF",
    padding: 16,
    gap: 16,
  },
  detailExamTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#111827",
  },
  detailExamSub: {
    fontSize: 13,
    color: "#7C8798",
    marginTop: 4,
  },
  detailInfoRow: {
    flexDirection: "row",
    gap: 12,
  },
  detailInfoChip: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#F8FAFC",
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: "#E5EAF3",
  },
  detailInfoIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: "#F2F4F7",
    alignItems: "center",
    justifyContent: "center",
  },
  detailInfoLabel: {
    fontSize: 12,
    color: "#98A2B3",
    marginBottom: 2,
  },
  detailInfoValue: {
    fontSize: 14,
    fontWeight: "600",
    color: "#111827",
  },
  detailSectionCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#D8E3FF",
    padding: 16,
    gap: 14,
  },
  detailSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  detailSectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111827",
  },
  ruleGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  ruleCard: {
    width: "48%",
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    gap: 6,
  },
  ruleCardWarning: {
    backgroundColor: "#FFF7ED",
    borderColor: "#FCD9A8",
  },
  ruleCardDanger: {
    backgroundColor: "#FEF2F2",
    borderColor: "#FECACA",
  },
  ruleTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#111827",
  },
  ruleSubtitle: {
    fontSize: 12,
    color: "#7C8798",
    lineHeight: 16,
  },
  durationHighlight: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#BFD1FF",
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: "center",
    gap: 4,
  },
  durationLabel: {
    fontSize: 12,
    color: "#7C8798",
  },
  durationValue: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111827",
  },
  scheduleRow: {
    flexDirection: "row",
    gap: 12,
  },
  scheduleCard: {
    flex: 1,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#D8E3FF",
    paddingVertical: 16,
    paddingHorizontal: 12,
    alignItems: "center",
    gap: 6,
    backgroundColor: "#FFFFFF",
  },
  scheduleCardGreen: {
    borderColor: "#BBF7D0",
  },
  scheduleLabel: {
    fontSize: 12,
    color: "#7C8798",
  },
  scheduleValue: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111827",
  },
});
