import { StyleSheet } from "react-native";

export const examStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#F2F4F7" },
  content: { padding: 20, paddingBottom: 40, gap: 16 },
  pageTitle: {
    fontSize: 26,
    fontWeight: "800",
    color: "#111",
    marginBottom: 4,
  },

  // ── Tab switcher (Шалгалтуудад / Шалгалтын түүх) ──
  tabRow: {
    flexDirection: "row",
    backgroundColor: "#ECEDF2",
    borderRadius: 14,
    padding: 4,
  },
  tab: {
    flex: 1,
    paddingVertical: 9,
    alignItems: "center",
    borderRadius: 11,
  },
  tabActive: {
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  tabText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#888",
  },
  tabTextActive: {
    color: "#111",
  },

  // ── Search bar ──
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 11,
    gap: 8,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: "#111",
  },
  searchIcon: {
    fontSize: 16,
    color: "#AAB0C0",
  },

  // ── Empty state ──
  emptyCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 28,
    alignItems: "center",
    gap: 12,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
  },
  emptyEmoji: { fontSize: 48 },
  emptyTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#111",
    textAlign: "center",
  },
  emptyText: {
    fontSize: 14,
    color: "#888",
    textAlign: "center",
    lineHeight: 20,
  },

  // ── Exam detail card (active exam header) ──
  examCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
  },
  examCardTop: { height: 5, backgroundColor: "#5B67F8" },
  examCardBody: { padding: 16, gap: 12 },
  examCardRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  avatar: {
    width: 46,
    height: 46,
    borderRadius: 14,
    backgroundColor: "#7C6FE0",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: { color: "#fff", fontSize: 18, fontWeight: "800" },
  examTitle: { fontSize: 15, fontWeight: "700", color: "#111" },
  examMeta: { fontSize: 12, color: "#888", marginTop: 2 },

  // ── List card (шалгалтын жагсаалтын card) ──
  listCard: {
    backgroundColor: "#fff",
    borderRadius: 18,
    padding: 16,
    gap: 6,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  listCardRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  listCardTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#111",
    flex: 1,
    marginRight: 8,
  },
  listCardMeta: {
    fontSize: 12,
    color: "#888",
    lineHeight: 19,
  },
  upcomingCard: {
    backgroundColor: "#fff",
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 14,
    gap: 14,
    borderWidth: 1,
    borderColor: "#DEE5FF",
    shadowColor: "#000",
    shadowOpacity: 0.03,
    shadowRadius: 8,
    elevation: 1,
  },
  upcomingCardTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#111827",
    flex: 1,
    marginRight: 10,
  },
  upcomingMetaGroup: {
    gap: 12,
    marginTop: 4,
  },
  upcomingMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  upcomingMetaLabel: {
    fontSize: 13,
    color: "#A3A3A3",
    flex: 1,
  },
  upcomingMetaValue: {
    fontSize: 14,
    fontWeight: "400",
    color: "#111827",
  },
  upcomingPrimaryButton: {
    marginTop: 6,
    marginLeft: "auto",
    minWidth: 146,
    backgroundColor: "#3568F5",
    borderRadius: 15,
    paddingVertical: 12,
    paddingHorizontal: 22,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#2F5BE3",
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 3,
  },
  upcomingButtonRow: {
    marginTop: 6,
    alignItems: "flex-end",
  },
  upcomingDetailButton: {
    minWidth: 146,
    backgroundColor: "#3568F5",
    borderRadius: 15,
    paddingVertical: 12,
    paddingHorizontal: 22,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#2F5BE3",
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 3,
  },
  upcomingDetailText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  upcomingDetailArrow: {
    fontSize: 28,
    lineHeight: 28,
    color: "#111827",
  },
  detailLink: {
    fontSize: 13,
    color: "#5B67F8",
    fontWeight: "600",
    marginTop: 4,
    alignSelf: "flex-end",
  },

  // ── Status pills ──
  statusPill: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 3,
    backgroundColor: "#E8FBEE",
  },
  statusPillWarning: { backgroundColor: "#FEF3C7" },
  statusPillDanger: { backgroundColor: "#FEE2E2" },
  statusPillText: { color: "#22C55E", fontSize: 11, fontWeight: "600" },
  statusPillTextWarning: { color: "#B45309" },
  statusPillTextDanger: { color: "#DC2626" },

  // ── Meta chips (remaining time / progress) ──
  metaRow: { flexDirection: "row", gap: 10 },
  metaChip: {
    flex: 1,
    backgroundColor: "#F2F4F7",
    borderRadius: 14,
    padding: 12,
    alignItems: "center",
  },
  metaChipLabel: { fontSize: 11, color: "#888", marginBottom: 4 },
  metaChipValue: { fontSize: 18, fontWeight: "800", color: "#111" },

  // ── Info / warning / error boxes ──
  infoBox: { backgroundColor: "#EEF4FF", borderRadius: 12, padding: 10 },
  infoText: { color: "#3657B0", fontSize: 13, lineHeight: 19 },
  warningBox: { backgroundColor: "#FEF3C7", borderRadius: 12, padding: 10 },
  warningText: { color: "#B45309", fontSize: 13 },
  errorText: { color: "#DC2626", fontSize: 13, textAlign: "center" },

  // ── Buttons ──
  primaryBtn: {
    backgroundColor: "#5B67F8",
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center",
  },
  primaryBtnText: { color: "#fff", fontWeight: "700", fontSize: 15 },
  secondaryBtn: {
    backgroundColor: "#F2F4F7",
    borderRadius: 14,
    paddingVertical: 13,
    alignItems: "center",
  },
  secondaryBtnText: { color: "#5B67F8", fontWeight: "600", fontSize: 15 },

  // ── Question card ──
  questionCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 20,
    gap: 14,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
  },
  questionCounter: { fontSize: 13, fontWeight: "700", color: "#5B67F8" },
  questionText: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111",
    lineHeight: 26,
  },
  questionImage: {
    width: "100%",
    height: 180,
    borderRadius: 14,
    backgroundColor: "#F2F4F7",
  },
  optionList: { gap: 10 },
  optionButton: {
    borderWidth: 1.5,
    borderColor: "#E0E3F0",
    borderRadius: 14,
    padding: 16,
    backgroundColor: "#F8F9FF",
  },
  optionButtonSelected: { borderColor: "#5B67F8", backgroundColor: "#ECEEFF" },
  optionLabel: { fontSize: 15, color: "#333", lineHeight: 22 },
  optionLabelSelected: { color: "#5B67F8", fontWeight: "700" },
  answerInput: {
    minHeight: 160,
    borderWidth: 1.5,
    borderColor: "#E0E3F0",
    borderRadius: 14,
    backgroundColor: "#F8F9FF",
    padding: 14,
    textAlignVertical: "top",
    fontSize: 15,
    color: "#111",
  },

  // ── Footer navigation ──
  footerActions: { gap: 10, paddingBottom: 8 },
  navBtn: {
    backgroundColor: "#F2F4F7",
    borderRadius: 14,
    paddingVertical: 13,
    alignItems: "center",
  },
  navBtnDisabled: { opacity: 0.4 },
  navBtnText: { color: "#5B67F8", fontWeight: "600", fontSize: 15 },

  detailOverlay: {
    flex: 1,
    backgroundColor: "#F8FAFC",
  },
  detailSheet: {
    backgroundColor: "#F8FAFC",
    flex: 1,
  },
  detailTopBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    minHeight: 46,
    paddingTop: 14,
    paddingBottom: 4,
  },
  detailBackButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  detailHeaderTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111827",
    lineHeight: 22,
  },
  detailHeaderSpacer: {
    width: 38,
  },
  detailContent: {
    padding: 16,
    gap: 18,
  },
  detailHeroCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#D8E3FF",
    padding: 16,
    gap: 16,
  },
  detailExamTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#111827",
  },
  detailExamSub: {
    fontSize: 13,
    color: "#7C8798",
    marginTop: 4,
  },
  detailInfoRow: {
    flexDirection: "row",
    gap: 12,
  },
  detailInfoChip: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#F8FAFC",
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: "#E5EAF3",
  },
  detailInfoIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: "#F2F4F7",
    alignItems: "center",
    justifyContent: "center",
  },
  detailInfoLabel: {
    fontSize: 12,
    color: "#98A2B3",
    marginBottom: 2,
  },
  detailInfoValue: {
    fontSize: 14,
    fontWeight: "600",
    color: "#111827",
  },
  detailSectionCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#D8E3FF",
    padding: 16,
    gap: 14,
  },
  detailSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  detailSectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111827",
  },
  ruleGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  ruleCard: {
    width: "48%",
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    gap: 6,
  },
  ruleCardWarning: {
    backgroundColor: "#FFF7ED",
    borderColor: "#FCD9A8",
  },
  ruleCardDanger: {
    backgroundColor: "#FEF2F2",
    borderColor: "#FECACA",
  },
  ruleTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#111827",
  },
  ruleSubtitle: {
    fontSize: 12,
    color: "#7C8798",
    lineHeight: 16,
  },
  durationHighlight: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#BFD1FF",
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: "center",
    gap: 4,
  },
  durationLabel: {
    fontSize: 12,
    color: "#7C8798",
  },
  durationValue: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111827",
  },
  scheduleRow: {
    flexDirection: "row",
    gap: 12,
  },
  scheduleCard: {
    flex: 1,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#D8E3FF",
    paddingVertical: 16,
    paddingHorizontal: 12,
    alignItems: "center",
    gap: 6,
    backgroundColor: "#FFFFFF",
  },
  scheduleCardGreen: {
    borderColor: "#BBF7D0",
  },
  scheduleLabel: {
    fontSize: 12,
    color: "#7C8798",
  },
  scheduleValue: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111827",
  },
});
