import { StyleSheet } from "react-native";

export const examStyles = StyleSheet.create({
  // Document 10-ийн бүх styles-ийг энд хуулна
  screen: { flex: 1, backgroundColor: "#F2F4F7" },
  content: { padding: 20, paddingBottom: 40, gap: 16 },
  pageTitle: {
    fontSize: 26,
    fontWeight: "800",
    color: "#111",
    marginBottom: 4,
  },
  emptyCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 28,
    alignItems: "center",
    gap: 12,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
  },
  emptyEmoji: { fontSize: 48 },
  emptyTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#111",
    textAlign: "center",
  },
  emptyText: {
    fontSize: 14,
    color: "#888",
    textAlign: "center",
    lineHeight: 20,
  },
  examCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
  },
  examCardTop: { height: 5, backgroundColor: "#5B67F8" },
  examCardBody: { padding: 16, gap: 12 },
  examCardRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  avatar: {
    width: 46,
    height: 46,
    borderRadius: 14,
    backgroundColor: "#7C6FE0",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: { color: "#fff", fontSize: 18, fontWeight: "800" },
  examTitle: { fontSize: 15, fontWeight: "700", color: "#111" },
  examMeta: { fontSize: 12, color: "#888", marginTop: 2 },
  statusPill: {
    backgroundColor: "#E8F5E9",
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  statusPillWarning: { backgroundColor: "#FEF3C7" },
  statusPillText: { color: "#2E7D32", fontSize: 11, fontWeight: "700" },
  statusPillTextWarning: { color: "#B45309" },
  metaRow: { flexDirection: "row", gap: 10 },
  metaChip: {
    flex: 1,
    backgroundColor: "#F2F4F7",
    borderRadius: 14,
    padding: 12,
    alignItems: "center",
  },
  metaChipLabel: { fontSize: 11, color: "#888", marginBottom: 4 },
  metaChipValue: { fontSize: 18, fontWeight: "800", color: "#111" },
  infoBox: {
    backgroundColor: "#EEF4FF",
    borderRadius: 12,
    padding: 10,
  },
  infoText: {
    color: "#3657B0",
    fontSize: 13,
    lineHeight: 19,
  },
  warningBox: { backgroundColor: "#FEF3C7", borderRadius: 12, padding: 10 },
  warningText: { color: "#B45309", fontSize: 13 },
  errorText: { color: "#DC2626", fontSize: 13, textAlign: "center" },
  primaryBtn: {
    backgroundColor: "#5B67F8",
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center",
    width: 200,
  },
  primaryBtnText: { color: "#fff", fontWeight: "700", fontSize: 15 },
  secondaryBtn: {
    backgroundColor: "#F2F4F7",
    borderRadius: 14,
    paddingVertical: 13,
    alignItems: "center",
    width: 200,
  },
  secondaryBtnText: {
    color: "#5B67F8",
    fontWeight: "600",
    fontSize: 15,
  },
  questionCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 20,
    gap: 14,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
  },
  questionCounter: { fontSize: 13, fontWeight: "700", color: "#5B67F8" },
  questionText: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111",
    lineHeight: 26,
  },
  questionImage: {
    width: "100%",
    height: 180,
    borderRadius: 14,
    backgroundColor: "#F2F4F7",
  },
  optionList: { gap: 10 },
  optionButton: {
    borderWidth: 1.5,
    borderColor: "#E0E3F0",
    borderRadius: 14,
    padding: 16,
    backgroundColor: "#F8F9FF",
  },
  optionButtonSelected: { borderColor: "#5B67F8", backgroundColor: "#ECEEFF" },
  optionLabel: { fontSize: 15, color: "#333", lineHeight: 22 },
  optionLabelSelected: { color: "#5B67F8", fontWeight: "700" },
  answerInput: {
    minHeight: 160,
    borderWidth: 1.5,
    borderColor: "#E0E3F0",
    borderRadius: 14,
    backgroundColor: "#F8F9FF",
    padding: 14,
    textAlignVertical: "top",
    fontSize: 15,
    color: "#111",
  },
  footerActions: { gap: 10, paddingBottom: 8 },
  navBtn: {
    backgroundColor: "#F2F4F7",
    borderRadius: 14,
    paddingVertical: 13,
    alignItems: "center",
  },
  navBtnDisabled: { opacity: 0.4 },
  navBtnText: { color: "#5B67F8", fontWeight: "600", fontSize: 15 },
});
