import { StyleSheet } from "react-native";

export const leaderboardStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#F2F4F7" },
  content: { padding: 20, paddingBottom: 40, gap: 14 },
  pageTitle: { fontSize: 24, fontWeight: "800", color: "#111" },
  pageSubtitle: { fontSize: 13, color: "#888", marginTop: 2 },
  tabRow: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 4,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  tab: { flex: 1, paddingVertical: 10, alignItems: "center", borderRadius: 11 },
  tabActive: { backgroundColor: "#F2F4F7" },
  tabText: { fontSize: 14, fontWeight: "600", color: "#888" },
  tabTextActive: { color: "#111", fontWeight: "700" },
  myRankBanner: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#6C5CE7",
    borderRadius: 18,
    padding: 16,
  },
  myRankLeft: { flexDirection: "row", alignItems: "center", gap: 12 },
  myRankTrophy: { fontSize: 28 },
  myRankTitle: { fontSize: 15, fontWeight: "800", color: "#fff" },
  myRankSub: { fontSize: 12, color: "rgba(255,255,255,0.8)", marginTop: 2 },
  myRankRight: { alignItems: "flex-end" },
  myRankNumber: { fontSize: 22, fontWeight: "900", color: "#fff" },
  myRankDelta: { fontSize: 12, color: "rgba(255,255,255,0.7)", marginTop: 2 },
  podiumRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "flex-end",
    gap: 8,
    paddingVertical: 8,
  },
  listCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
    overflow: "hidden",
  },
  listRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#F2F4F7",
  },
  listRowActive: { backgroundColor: "#F5F3FF" },
  rankBadge: {
    width: 30,
    height: 30,
    borderRadius: 10,
    backgroundColor: "#F2F4F7",
    alignItems: "center",
    justifyContent: "center",
  },
  rankBadgeActive: { backgroundColor: "#6C5CE7" },
  rankText: { fontSize: 14, fontWeight: "800", color: "#555" },
  rankTextActive: { color: "#fff" },
  listAvatar: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  listAvatarEmoji: { fontSize: 22 },
  nameRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  listName: { fontSize: 15, fontWeight: "700", color: "#111" },
  youBadge: {
    backgroundColor: "#6C5CE7",
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  youBadgeText: { fontSize: 10, fontWeight: "800", color: "#fff" },
  listLevel: { fontSize: 12, color: "#888", marginTop: 1 },
  listRight: { alignItems: "flex-end", gap: 4 },
  listXp: { fontSize: 13, fontWeight: "700", color: "#111" },
  scoreBadge: { borderRadius: 8, paddingHorizontal: 8, paddingVertical: 3 },
  scoreText: { fontSize: 12, fontWeight: "700" },
  emptyWrap: { padding: 32, alignItems: "center", gap: 10 },
  emptyEmoji: { fontSize: 40 },
  emptyText: { fontSize: 14, color: "#888", textAlign: "center" },
});

export const podStyles = StyleSheet.create({
  wrap: { alignItems: "center", flex: 1, gap: 4 },
  crown: { fontSize: 24, marginBottom: 2 },
  avatar: {
    width: 54,
    height: 54,
    borderRadius: 16,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#F5A623",
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
    zIndex: 1,
  },
  avatarLarge: { width: 64, height: 64, borderRadius: 18 },
  avatarEmoji: { fontSize: 28 },
  podium: {
    width: "90%",
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    alignItems: "center",
    justifyContent: "flex-start",
    paddingTop: 8,
  },
  podiumRank: { fontSize: 20, fontWeight: "900", color: "#fff" },
  podiumName: {
    fontSize: 13,
    fontWeight: "700",
    color: "#111",
    textAlign: "center",
  },
  podiumXp: { fontSize: 11, color: "#888", textAlign: "center" },
});
