import { StyleSheet } from "react-native";

export const profileStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#F7FAFC",
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 22,
    paddingBottom: 36,
  },
  hero: {
    alignItems: "center",
    marginBottom: -42,
    zIndex: 2,
  },
  avatarShell: {
    width: 150,
    height: 150,
    borderRadius: 75,
    borderWidth: 2,
    borderColor: "#0FC6FF",
    backgroundColor: "#FFFFFF",
    overflow: "hidden",
    shadowColor: "#00779A",
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 8,
  },
  avatarImage: {
    width: "100%",
    height: "100%",
  },
  avatarFallback: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#DDF7FF",
  },
  avatarInitials: {
    fontSize: 42,
    fontWeight: "800",
    color: "#00779A",
  },
  profileCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    paddingTop: 56,
    paddingHorizontal: 16,
    paddingBottom: 18,
    borderWidth: 1,
    borderColor: "#D8F1FA",
    shadowColor: "#A5D9E8",
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 6,
    marginBottom: 16,
  },
  profileHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 18,
  },
  profileHeaderText: {
    flex: 1,
    paddingRight: 12,
  },
  profileName: {
    fontSize: 18,
    fontWeight: "800",
    color: "#00779A",
    marginBottom: 2,
  },
  profileRole: {
    fontSize: 15,
    color: "#3A9ABB",
  },
  editButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 1,
    borderColor: "#0FC6FF",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
  },
  xpRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  xpLabel: {
    fontSize: 15,
    color: "#8696A8",
  },
  xpValue: {
    fontSize: 15,
    color: "#8696A8",
  },
  progressTrack: {
    height: 12,
    borderRadius: 999,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#CFEAF3",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: "#1BCBF5",
  },
  featureRow: {
    flexDirection: "row",
    gap: 14,
    marginBottom: 16,
  },
  featureCard: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#A8E7FA",
    paddingVertical: 18,
    paddingHorizontal: 12,
    alignItems: "center",
    minHeight: 94,
  },
  featureIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#00779A",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  featureTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#00779A",
    marginBottom: 6,
  },
  featureSubtitle: {
    fontSize: 13,
    color: "#8B97A6",
    textAlign: "center",
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#1E2630",
  },
  sectionMeta: {
    fontSize: 13,
    color: "#9AA7B7",
  },
  achievementRow: {
    flexDirection: "row",
    gap: 14,
    marginBottom: 16,
  },
  achievementCard: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#A8E7FA",
    paddingVertical: 16,
    paddingHorizontal: 12,
    alignItems: "center",
    minHeight: 112,
  },
  achievementIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  achievementIcon: {
    fontSize: 22,
  },
  achievementTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#00779A",
    textAlign: "center",
    marginBottom: 6,
  },
  achievementSubtitle: {
    fontSize: 13,
    color: "#8B97A6",
    textAlign: "center",
  },
  menuCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#A8E7FA",
    overflow: "hidden",
    marginBottom: 14,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 12,
  },
  menuIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F1FBFF",
  },
  menuCopy: {
    flex: 1,
  },
  menuLabel: {
    fontSize: 15,
    fontWeight: "700",
    color: "#00779A",
    marginBottom: 2,
  },
  menuSub: {
    fontSize: 13,
    color: "#8B97A6",
  },
  menuDivider: {
    height: 1,
    backgroundColor: "#E8F6FB",
    marginHorizontal: 14,
  },
  panelCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#A8E7FA",
    padding: 16,
    marginBottom: 14,
    gap: 12,
  },
  panelTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: "#1E2630",
  },
  panelText: {
    fontSize: 13,
    color: "#8B97A6",
    lineHeight: 20,
  },
  selectorOption: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#D8F1FA",
    backgroundColor: "#FBFEFF",
  },
  selectorOptionSelected: {
    backgroundColor: "#F1FBFF",
    borderColor: "#0FC6FF",
  },
  selectorName: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1E2630",
  },
  selectorCode: {
    fontSize: 13,
    color: "#8B97A6",
    marginTop: 2,
  },
  feedbackText: {
    fontSize: 13,
    textAlign: "center",
  },
  actionButton: {
    backgroundColor: "#10BFF0",
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center",
  },
  actionButtonText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "700",
  },
  buttonDisabled: {
    opacity: 0.45,
  },
});

export const achStyles = StyleSheet.create({});
