import { StyleSheet } from "react-native";

const AVATAR_SIZE = 166;
const AVATAR_OVERLAP = 46;

export const profileStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#F0F4FF",
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 36,
  },

  profileCardWrapper: {
    position: "relative",
    marginBottom: 14,
    paddingTop: AVATAR_SIZE - AVATAR_OVERLAP,
  },
  profileBackdrop: {
    ...StyleSheet.absoluteFillObject,
    overflow: "hidden",
    borderRadius: 30,
  },
  backdropOrb: {
    position: "absolute",
    borderRadius: 999,
  },
  backdropOrbLeft: {
    top: 18,
    left: -10,
    width: 180,
    height: 180,
  },
  backdropOrbRight: {
    top: 104,
    right: -54,
    width: 232,
    height: 232,
  },

  avatarContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    alignItems: "center",
    zIndex: 10,
  },
  avatarShadow: {
    position: "absolute",
    bottom: -22,
    width: 142,
    height: 54,
    borderRadius: 999,
    backgroundColor: "rgba(15,23,42,0.28)",
    shadowColor: "#0F172A",
    shadowOpacity: 0.24,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 12 },
    elevation: 10,
  },
  avatarShell: {
    width: AVATAR_SIZE,
    height: AVATAR_SIZE,
    borderRadius: AVATAR_SIZE / 2,
    borderWidth: 3,
    borderColor: "#2563EB",
    backgroundColor: "#E0F2FE",
    overflow: "hidden",
    shadowColor: "#2563EB",
    shadowOpacity: 0.24,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 12,
  },
  avatarImage: {
    width: "100%",
    height: "100%",
  },
  avatarImageDefault: {
    transform: [{ scale: 1.18 }],
  },
  avatarBottomFade: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: AVATAR_SIZE * 0.4,
  },
  avatarFallback: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EFF6FF",
  },
  avatarInitials: {
    fontSize: 40,
    fontWeight: "800",
    color: "#2563EB",
  },
  profileCard: {
    position: "relative",
    overflow: "hidden",
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.55)",
    backgroundColor: "rgba(255,255,255,0.2)",
    paddingTop: AVATAR_OVERLAP + 8,
    shadowColor: "#2563EB",
    shadowOpacity: 0.12,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  profileCardBlur: {
    ...StyleSheet.absoluteFillObject,
  },
  profileCardHighlight: {
    ...StyleSheet.absoluteFillObject,
  },
  profileCardContent: {
    position: "relative",
    zIndex: 1,
  },
  cardHandle: {
    width: 32,
    height: 3,
    borderRadius: 999,
    backgroundColor: "#CBD5E1",
    alignSelf: "center",
    marginBottom: 8,
  },
  nameCard: {
    marginHorizontal: 12,
    marginBottom: 10,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.5)",
    backgroundColor: "rgba(255,255,255,0.18)",
  },
  profileHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  profileHeaderText: {
    flex: 1,
    paddingRight: 12,
  },
  profileName: {
    fontSize: 20,
    fontWeight: "800",
    color: "#1E293B",
    marginBottom: 1,
  },
  profileRole: {
    fontSize: 13,
    color: "#475569",
  },
  editButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: "#2563EB",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.68)",
    shadowColor: "#2563EB",
    shadowOpacity: 0.12,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  xpSection: {
    paddingHorizontal: 16,
    paddingTop: 2,
    paddingBottom: 18,
  },
  xpRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  xpLabel: {
    fontSize: 12,
    color: "#94A3B8",
    fontWeight: "600",
  },
  xpValue: {
    fontSize: 12,
    color: "#94A3B8",
    fontWeight: "600",
  },
  progressTrack: {
    height: 9,
    borderRadius: 999,
    backgroundColor: "rgba(148,163,184,0.18)",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: "#2563EB",
  },

  // ─── Feature cards (English / %) ───────────────────────────────────────────
  featureRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 14,
  },
  featureCard: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#DBEAFE",
    paddingVertical: 18,
    paddingHorizontal: 12,
    alignItems: "center",
    minHeight: 100,
    shadowColor: "#2563EB",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  featureIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "#2563EB",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  featureTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1E293B",
    marginBottom: 4,
  },
  featureSubtitle: {
    fontSize: 12,
    color: "#94A3B8",
    textAlign: "center",
  },

  // ─── Achievements ───────────────────────────────────────────────────────────
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#1E293B",
  },
  sectionMeta: {
    fontSize: 13,
    color: "#94A3B8",
  },
  achievementRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 16,
  },
  achievementCard: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#DBEAFE",
    paddingVertical: 16,
    paddingHorizontal: 12,
    alignItems: "center",
    minHeight: 112,
    shadowColor: "#2563EB",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  achievementIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  achievementIcon: {
    fontSize: 22,
  },
  achievementTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1E293B",
    textAlign: "center",
    marginBottom: 4,
  },
  achievementSubtitle: {
    fontSize: 12,
    color: "#94A3B8",
    textAlign: "center",
  },

  // ─── Menu ──────────────────────────────────────────────────────────────────
  menuCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#DBEAFE",
    overflow: "hidden",
    marginBottom: 14,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 12,
  },
  menuIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EFF6FF",
  },
  menuCopy: {
    flex: 1,
  },
  menuLabel: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1E293B",
    marginBottom: 2,
  },
  menuSub: {
    fontSize: 13,
    color: "#94A3B8",
  },
  menuDivider: {
    height: 1,
    backgroundColor: "#F1F5F9",
    marginHorizontal: 14,
  },

  // ─── Panels (editor / code login / user switcher) ──────────────────────────
  panelCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#DBEAFE",
    padding: 16,
    marginBottom: 14,
    gap: 12,
  },
  panelTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: "#1E293B",
  },
  panelText: {
    fontSize: 13,
    color: "#94A3B8",
    lineHeight: 20,
  },
  selectorOption: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#DBEAFE",
    backgroundColor: "#FAFBFF",
  },
  selectorOptionSelected: {
    backgroundColor: "#EFF6FF",
    borderColor: "#2563EB",
  },
  selectorName: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1E293B",
  },
  selectorCode: {
    fontSize: 13,
    color: "#94A3B8",
    marginTop: 2,
  },
  feedbackText: {
    fontSize: 13,
    textAlign: "center",
  },
  actionButton: {
    backgroundColor: "#2563EB",
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center",
  },
  actionButtonText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "700",
  },
  buttonDisabled: {
    opacity: 0.45,
  },
});

export const achStyles = StyleSheet.create({});
