import { StyleSheet } from "react-native";

export const profileStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#F2F4F7" },
  content: { padding: 20, paddingBottom: 40, gap: 14 },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  pageTitle: { fontSize: 24, fontWeight: "800", color: "#111" },
  settingsBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 18,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
    gap: 12,
  },
  profileRow: { flexDirection: "row", alignItems: "center", gap: 14 },
  avatarWrap: {
    width: 64,
    height: 64,
    borderRadius: 18,
    backgroundColor: "#DDD6FE",
    alignItems: "center",
    justifyContent: "center",
    overflow: "visible",
  },
  avatarImage: { width: 64, height: 64, borderRadius: 18 },
  avatarInitials: { fontSize: 24, fontWeight: "800", color: "#6C5CE7" },
  avatarBadge: {
    position: "absolute",
    bottom: -6,
    right: -6,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "#FEF3C7",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#fff",
  },
  avatarBadgeText: { fontSize: 11 },
  nameRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  profileName: { fontSize: 20, fontWeight: "800", color: "#111" },
  levelBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    backgroundColor: "#EEF2FF",
    borderRadius: 20,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  levelText: { fontSize: 12, fontWeight: "700", color: "#6C5CE7" },
  profileEmail: { fontSize: 13, color: "#888", marginTop: 2 },
  statsRow: { flexDirection: "row", gap: 12 },
  statCard: {
    flex: 1,
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 18,
    alignItems: "center",
    gap: 6,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
  },
  statIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: "#FEF3C7",
    alignItems: "center",
    justifyContent: "center",
  },
  statIcon: { fontSize: 22 },
  statBigValue: { fontSize: 22, fontWeight: "800", color: "#111" },
  statLabel: { fontSize: 12, color: "#888", textAlign: "center" },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  sectionTitle: { fontSize: 17, fontWeight: "800", color: "#111" },
  sectionMeta: { fontSize: 13, color: "#5B67F8", fontWeight: "600" },
  achRow: { flexDirection: "row", gap: 12 },
  menuCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
    overflow: "hidden",
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    padding: 16,
  },
  menuIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  menuLabel: { fontSize: 15, fontWeight: "700", color: "#111" },
  menuSub: { fontSize: 12, color: "#888", marginTop: 1 },
  menuDivider: { height: 1, backgroundColor: "#F2F4F7", marginHorizontal: 16 },
  selectorOption: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 14,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: "#E0E3F0",
    backgroundColor: "#F8F9FF",
  },
  selectorOptionSelected: {
    borderColor: "#5B67F8",
    backgroundColor: "#ECEEFF",
  },
  selectorName: { fontSize: 15, fontWeight: "700", color: "#111" },
  selectorCode: { fontSize: 12, color: "#888", marginTop: 2 },
  saveBtn: {
    backgroundColor: "#5B67F8",
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center",
  },
  saveBtnText: { color: "#fff", fontWeight: "700", fontSize: 15 },
});

export const achStyles = StyleSheet.create({
  card: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 16,
    alignItems: "center",
    gap: 8,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
  },
  iconWrap: {
    width: 60,
    height: 60,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  iconText: { fontSize: 28 },
  label: {
    fontSize: 14,
    fontWeight: "800",
    color: "#111",
    textAlign: "center",
  },
  desc: { fontSize: 11, color: "#888", textAlign: "center", lineHeight: 16 },
});
