import { StyleSheet } from "react-native";

export const progressStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#F2F4F7" },
  content: { padding: 20, paddingBottom: 40, gap: 16 },
  pageTitle: { fontSize: 24, fontWeight: "800", color: "#111" },
  pageSubtitle: { fontSize: 14, color: "#888", marginTop: 2 },
  periodRow: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 4,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  periodBtn: {
    flex: 1,
    paddingVertical: 10,
    alignItems: "center",
    borderRadius: 11,
  },
  periodBtnActive: { backgroundColor: "#5B67F8" },
  periodBtnText: { fontSize: 14, fontWeight: "600", color: "#888" },
  periodBtnTextActive: { color: "#fff", fontWeight: "700" },
  card: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 18,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
  },
  cardTitle: { fontSize: 16, fontWeight: "800", color: "#111" },
  cardSubtitle: { fontSize: 13, color: "#888", marginTop: 2 },
  trendHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 16,
  },
  trendBadge: {
    backgroundColor: "#DCFCE7",
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  trendBadgeText: { color: "#16A34A", fontWeight: "700", fontSize: 13 },
  statsRow: { flexDirection: "row", gap: 10 },
  statCard: {
    flex: 1,
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 14,
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  statValue: { fontSize: 20, fontWeight: "800", color: "#111" },
  statLabel: { fontSize: 11, color: "#888", marginTop: 2, textAlign: "center" },

  // Богино кодоос авсан styles
  historyTitle: { fontSize: 18, fontWeight: "800", color: "#203229" },
  historyRow: {
    borderTopWidth: 1,
    borderTopColor: "#EFE5D4",
    paddingTop: 14,
    gap: 6,
  },
  historyHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
    alignItems: "center",
  },
  historyName: { flex: 1, fontSize: 15, fontWeight: "700", color: "#24392F" },
  historyMeta: { fontSize: 13, color: "#6E6A62" },
  emptyText: { fontSize: 14, lineHeight: 21, color: "#5F665E" },
});
